### ISSUE TITLE
Updating

### ISSUE THREAD

**Issue by larscom** [alex1701c/JetBrainsRunner#19]
Thanks for this wonderful plugin!

How can i update? I get a notification to update.

I am currently on version 1.7.0, running the installer script again doesn't bring me to 1.7.1

**Comment by ghost** [comment]
It is just a metadata error. The program itself is up to date, but it thinks that it is not because a variable is not set correctly.

https://github.com/alex1701c/JetBrainsRunner/blob/eae8b1a78add5f6bf097e643856e514fc18aab36/CMakeLists.txt#L5

Still has 1.7.0

@larscom if you want to hotfix it locally for yourself as to not have the update notification pop up, just change that bit to 1.7.1 before installing.

**Comment by alex1701c** [comment]
Apologies, I forgot to manually update the entry after creating the tag on github. I have updated the release tar & the file on the KDE Store to include https://github.com/alex1701c/JetBrainsRunner/commit/48320883a4fb0a34410f5caa9d3ce341927932cf
